image: gradle:alpine
# A comment
before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
build:
  stage: build
  script: gradle --build-cache assemble
  artifacts:
    name: "hrfront-0.0.1-SNAPSHOT"
    paths:
      - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
